# Generated by Django 4.2.10 on 2025-04-02 20:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('last_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
